title: Pablo Frank
description: This website contains information about my teaching, advising, and research.
theme: just-the-docs

url: https://frankpablo.github.io/smith-site
logo: "/assets/images/pabloFaceIcon.png"
favicon_ico: "/assets/images/favicon.ico"
#color_scheme: dark